---
title: "DevAPAdb"
title-block-banner: true
author:
  - name: Jinlong Ru
    orcid: 0000-0002-6757-6018
    corresponding: true
date: 2023-06-03
toc: true
toc-depth: 4
number-sections: true
code-fold: true
code-line-numbers: true
code-tools: true
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    page-layout: article
    theme: 
      light: flatly
      dark: darkly
reference-location: margin
citation-location: margin
bibliography: refs.bib
cls: bioinformatics.csl
params:
  name: "02-app"
---

Updated: `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'CET')` CET.


```{r setup}
#| message: false
#| include: false
here::i_am(paste0(params$name, ".qmd"), uuid = "7a1b7392-66f2-442d-963b-c8434b6c5c3f")
projthis::proj_create_dir_target(params$name, clean = FALSE)
path_target <- projthis::proj_path_target(params$name)
path_source <- projthis::proj_path_source(params$name)
path_data <- path_source("00-raw", params$name)
dir.create(path_data, recursive = T)
```

The purpose of this document is ...

```{r packages}
#| cache: true
library(here)
library(conflicted)
devtools::load_all()
```

## Tasks

The first task is ...

